package euler.solutions;

import java.math.BigInteger;
import java.util.HashSet;

// How many distinct terms are in the sequence generated by a^b for 2 <= a <= 100 and 2 <= b <= 100?
public class Solution029 {

  public static String getAnswer() {
    HashSet<BigInteger> uniqueList = new HashSet<BigInteger>();
    BigInteger oneHundred = new BigInteger("100");
    BigInteger a;
    for (a = BigInteger.TWO; a.compareTo(oneHundred) <= 0; a = a.add(BigInteger.ONE)) {
      for (int b = 2; b <= 100; b++) {
        uniqueList.add(a.pow(b));
      }
    }
    return Integer.toString(uniqueList.size());
  }
}
